<?php

namespace app\index\controller;

use app\common\controller\Pc;
use think\Db;


class Index extends Pc
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        if (session("user")) {
            $captcha = Db::name("user")->where(['id' => session("user.id")])->find();
            if (empty($captcha)) {
                session("user", null);
                exit($this->redirect("index/index"));
            } else {
                //判断当前用户是否已将完成验证注册
                $capchas = Db::name("send_email")->where(['account' => $captcha['email'], "state" => 2, "type" => 1])->count();
                if ($capchas < 1) {
                    exit($this->redirect("sign/email_login?uid=" . session("user.id")));
                }
            }

        }
    }

    public function index()
    {
        return $this->fetch();
    }

    public function edit_blog()
    {
        if ($this->request->isMobile()) {
            return $this->fetch("/site_close");
        }
        if ($this->request->isAjax() && $this->request->isPost()) {
            $data = $this->request->param();
            if (empty($data['content'])) $this->error("内容不能为空");
            $condition = [];
            $data['status'] = 2;
            $data['add_time'] = $data['update_time'] = time();
            $data['is_comment'] = isset($data['is_comment']) && $data['is_comment'] == "on" ? 1 : 2;
            $data['author'] = session("user.id");
            $data['from'] = 1;
            $data['content'] = htmlspecialchars($data['content']);
            if (isset($data['id']) && !empty($data['id'])) {
                $condition['id'] = $data['id'];
                unset($data['id']);
                unset($data['add_time']);
            }

            if($condition){
                $id = Db::name("blog_item")->where($condition)->update($data);
            }else{
                $id = Db::name("blog_item")->insertGetId($data);
            }

            if($id === false) $this->error("保存失败");
            $this->success("保存成功");
            exit;
        }
        return $this->fetch();
    }

    public function blog_detail()
    {
        return $this->fetch();
    }

    public function blog_list()
    {
        $this->request->param();
        return $this->fetch();
    }

    public function register()
    {
        return $this->fetch("register1");
    }
}

